# Generated by Django 2.2.12 on 2021-02-10 01:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Building', '0002_initial2'),
        ('Survey', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AMTFoundation',
            fields=[
                ('foundation_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Building.Foundation')),
                ('amt_username', models.CharField(default='admin', max_length=50)),
                ('amt_password', models.CharField(max_length=50)),
                ('amt_ip_address', models.CharField(max_length=30)),
                ('plot', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Survey.Plot')),
            ],
            options={
                'default_permissions': (),
            },
            bases=('Building.foundation',),
        ),
    ]
