# Generated by Django 2.2.12 on 2021-02-11 00:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Building', '0002_initial2'),
    ]

    operations = [
        migrations.CreateModel(
            name='AWSEC2Foundation',
            fields=[
                ('foundation_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Building.Foundation')),
                ('awsec2_instance_id', models.CharField(blank=True, max_length=19, null=True)),
            ],
            bases=('Building.foundation',),
        ),
    ]
