# Generated by Django 2.2.12 on 2021-08-18 22:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Building', '0002_initial2'),
    ]

    operations = [
        migrations.CreateModel(
            name='PacketComplex',
            fields=[
                ('complex_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Building.Complex')),
                ('packet_auth_token', models.CharField(max_length=32)),
                ('packet_facility', models.CharField(max_length=36)),
                ('packet_project', models.CharField(max_length=36)),
            ],
            options={
                'default_permissions': (),
            },
            bases=('Building.complex',),
        ),
        migrations.CreateModel(
            name='PacketFoundation',
            fields=[
                ('foundation_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Building.Foundation')),
                ('packet_uuid', models.CharField(max_length=36)),
                ('packet_complex', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Packet.PacketComplex')),
            ],
            options={
                'default_permissions': (),
            },
            bases=('Building.foundation',),
        ),
    ]
