# Generated by Django 3.2.12 on 2025-02-11 03:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Building', '0002_initial2'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestComplex',
            fields=[
                ('complex_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Building.complex')),
            ],
            options={
                'default_permissions': (),
            },
            bases=('Building.complex',),
        ),
        migrations.CreateModel(
            name='TestFoundation',
            fields=[
                ('foundation_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Building.foundation')),
                ('test_delay_variance', models.IntegerField(default=30, help_text='In Seconds')),
                ('test_fail_likelihood', models.IntegerField(default=0, help_text='Likelyhood of failures per 1000, per "run" execution (ie: the longer the delay the more likely), if greater than 9, Unrecoverable errors my happen, 0 to disable')),
            ],
            options={
                'default_permissions': (),
            },
            bases=('Building.foundation',),
        ),
        migrations.CreateModel(
            name='TestComplexedFoundation',
            fields=[
                ('foundation_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Building.foundation')),
                ('complex_host', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Test.testcomplex')),
            ],
            options={
                'default_permissions': (),
            },
            bases=('Building.foundation',),
        ),
    ]
