# Generated by Django 2.2.12 on 2021-02-10 01:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Building', '0002_initial2'),
    ]

    operations = [
        migrations.CreateModel(
            name='AzureComplex',
            fields=[
                ('complex_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Building.Complex')),
                ('azure_subscription_id', models.CharField(max_length=36)),
                ('azure_location', models.CharField(max_length=20)),
                ('azure_resource_group', models.CharField(max_length=90)),
                ('azure_client_id', models.CharField(help_text='also called App Id', max_length=36)),
                ('azure_password', models.CharField(max_length=36)),
                ('azure_tenant_id', models.CharField(max_length=36)),
            ],
            options={
                'default_permissions': (),
            },
            bases=('Building.complex',),
        ),
        migrations.CreateModel(
            name='AzureFoundation',
            fields=[
                ('foundation_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Building.Foundation')),
                ('azure_resource_name', models.CharField(blank=True, max_length=64, null=True)),
                ('azure_complex', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Azure.AzureComplex')),
            ],
            options={
                'default_permissions': (),
            },
            bases=('Building.foundation',),
        ),
    ]
