# Generated by Django 2.2.12 on 2021-02-10 01:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Building', '0002_initial2'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProxmoxComplex',
            fields=[
                ('complex_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Building.Complex')),
                ('proxmox_username', models.CharField(max_length=50)),
                ('proxmox_password', models.CharField(max_length=50)),
            ],
            options={
                'default_permissions': (),
            },
            bases=('Building.complex',),
        ),
        migrations.CreateModel(
            name='ProxmoxFoundation',
            fields=[
                ('foundation_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Building.Foundation')),
                ('proxmox_vmid', models.IntegerField(blank=True, null=True)),
                ('proxmox_complex', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Proxmox.ProxmoxComplex')),
            ],
            options={
                'default_permissions': (),
                'unique_together': {('proxmox_complex', 'proxmox_vmid')},
            },
            bases=('Building.foundation',),
        ),
    ]
