# Generated by Django 4.2.11 on 2026-01-08 04:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Building', '0002_initial2'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProxmoxComplex',
            fields=[
                ('complex_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Building.complex')),
                ('proxmox_username', models.CharField(max_length=50)),
                ('proxmox_password', models.CharField(max_length=50)),
                ('proxmox_host', models.ForeignKey(help_text='set to Proxmox host', on_delete=django.db.models.deletion.PROTECT, to='Building.structure')),
            ],
            options={
                'default_permissions': (),
            },
            bases=('Building.complex',),
        ),
        migrations.CreateModel(
            name='ProxmoxFoundation',
            fields=[
                ('foundation_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Building.foundation')),
                ('proxmox_id', models.IntegerField(blank=True, null=True)),
                ('proxmox_complex', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Proxmox.proxmoxcomplex')),
            ],
            options={
                'default_permissions': (),
            },
            bases=('Building.foundation',),
        ),
    ]
