# Generated by Django 2.2.12 on 2021-02-10 01:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Building', '0002_initial2'),
    ]

    operations = [
        migrations.CreateModel(
            name='VCenterComplex',
            fields=[
                ('complex_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Building.Complex')),
                ('vcenter_username', models.CharField(max_length=50)),
                ('vcenter_password', models.CharField(max_length=50)),
                ('vcenter_datacenter', models.CharField(help_text='set to "ha-datacenter" for ESX hosts', max_length=50)),
                ('vcenter_cluster', models.CharField(help_text='set to the hostname (ie: "localhost.") for ESX hosts', max_length=50)),
                ('vcenter_host', models.ForeignKey(help_text='set to VCenter or the ESX host, if ESX host, leave members empty', on_delete=django.db.models.deletion.PROTECT, to='Building.Structure')),
            ],
            options={
                'default_permissions': (),
            },
            bases=('Building.complex',),
        ),
        migrations.CreateModel(
            name='VCenterFoundation',
            fields=[
                ('foundation_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Building.Foundation')),
                ('vcenter_uuid', models.CharField(blank=True, max_length=36, null=True)),
                ('vcenter_complex', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='VCenter.VCenterComplex')),
            ],
            options={
                'default_permissions': (),
            },
            bases=('Building.foundation',),
        ),
    ]
