# Generated by Django 4.2.11 on 2025-09-10 18:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Building', '0002_initial2'),
    ]

    operations = [
        migrations.CreateModel(
            name='LibVirtComplex',
            fields=[
                ('complex_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Building.complex')),
            ],
            options={
                'default_permissions': (),
            },
            bases=('Building.complex',),
        ),
        migrations.CreateModel(
            name='LibVirtFoundation',
            fields=[
                ('foundation_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Building.foundation')),
                ('libvirt_uuid', models.CharField(blank=True, max_length=36, null=True)),
                ('libvirt_complex', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='LibVirt.libvirtcomplex')),
            ],
            options={
                'default_permissions': (),
            },
            bases=('Building.foundation',),
        ),
    ]
