# Generated by Django 2.2.12 on 2020-12-23 22:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Building', '0002_initial2'),
    ]

    operations = [
        migrations.CreateModel(
            name='VirtualBoxComplex',
            fields=[
                ('complex_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Building.Complex')),
                ('virtualbox_username', models.CharField(max_length=50)),
                ('virtualbox_password', models.CharField(max_length=50)),
            ],
            options={
                'default_permissions': (),
            },
            bases=('Building.complex',),
        ),
        migrations.CreateModel(
            name='VirtualBoxFoundation',
            fields=[
                ('foundation_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Building.Foundation')),
                ('virtualbox_uuid', models.CharField(blank=True, max_length=36, null=True)),
                ('virtualbox_complex', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='VirtualBox.VirtualBoxComplex')),
            ],
            options={
                'default_permissions': (),
            },
            bases=('Building.foundation',),
        ),
    ]
